CREATE TABLE Supplier (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(256) NOT NULL ,
  inventoryApi VARCHAR(256) NOT NULL
);

CREATE TABLE Product (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(256) NOT NULL ,
  supplierId INTEGER NOT NULL
);

ALTER TABLE Product ADD FOREIGN KEY (supplierId) REFERENCES Supplier(id);

